#!/bin/bash

function compile(){
  echo "==> compiling for $DOCKER_TAG"  
  docker run --rm -t \
  -e CGO_ENABLED=0 \
  -e GOOS=linux \
  -e GOARCH=$DOCKER_TAG \
  -v $(pwd):/data \
  golang:1.8 bash -c \
  "apt-get update && apt-get install -y gccgo gcc \
  && go get -v -d github.com/ehazlett/certm \
  && cd \$GOPATH/src/github.com/ehazlett/certm \
  && export COMMIT=`git rev-parse --short HEAD` \
  && echo 'get deps' \
  && go get -v -d ./... \
  ; echo 'cleanup' \
  && rm -rf /go/src/github.com/Sirupsen \
  && find /go/src/ -type f -name '*.go' | xargs perl -i -pne 's|Sirupsen|sirupsen|' \
  && go get -v -d ./... \
  && echo 'start compiling' \
  && go build -a -tags 'netgo' -o /data/certm-\$GOARCH --installsuffix cgo \
  --ldflags='-s -w -linkmode external -extldflags -static \
  -X github.com/ehazlett/certm/version.GitCommit=\${COMMIT}'"
}

compile


